version: "3.6"

services:

  kafka-mirror:
    build:
      context: ./
      args:
        PYTHON_VER: ${PYTHON_VER}
        LIBCITISIM_VER: ${LIBCITISIM_VER}
    image: kafka-connector-citisim:${DOCKER_IMAGE_TAG}
    container_name: kafka-connector-citisim
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER:-127.0.0.1:9092}
